# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tyler Lutz
email: tlutzdesigns@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Providing simple and easy to follow AngularJS tutorials since 2016! For more information, view my GitHub repos. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tyler_lutz12
github_username:  tylerlutz

# Build settings
markdown: kramdown
